steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', '${_CF_NAME}', '--trigger-http', '--entry-point', 'main', '--runtime', 'python38', '--allow-unauthenticated']
  dir: 'gcp_func'